### ISSUE TITLE
RPC integration tests are failing on testnet

### ISSUE THREAD

**Issue by okovalov** [FindoraNetwork/platform#107]
### Problem Description

RPC integration tests are failing on testnet `https://prod-testnet.prod.findora.org:8545`

it might be related to the issue with the CLI (when trying to check balance using cli, it throws an unhandeled error 

```
~/p/Findora  ./fn account -a 0x9257e1aeb58e16a9c33e0e8469a1d5205d6350b8                                                       [01:19:10pm]
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { code: ParseError, message: "Parse error. Invalid JSON", data: Some("expected value at line 1 column 1") }', src/components/finutils/src/common/evm.rs:169:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

so when I am trying to run integration test, it also fails..

```
console.log
    🚀 ~ rpcParams.rpcUrl https://prod-testnet.prod.findora.org:8545
      at Object.<anonymous> (src/evm/rpc.integration.spec.ts:30:9)

console.log
    🚀 ~ IT IS SENDING file: rpc.spec.ts ~ line 37 ~ payload {
      method: 'eth_sendTransaction',
      params: [
        {
          gas: '0xf4240',
          gasPrice: '0x2540be401',
          from: '0x9257e1aeb58e16a9c33e0e8469a1d5205d6350b8',
          to: '0x0a9dfacdeed4f3d433998b6a80ce0a272715e125',
          value: '0x16345785d8a0000'
        }
      ],
      callback: undefined
    }

      at src/evm/rpc.integration.spec.ts:55:15

  console.log
    🚀 ~ IT IS SENT file: rpc.spec.ts ~ line 40 ~ payload {
      method: 'eth_sendTransaction',
      params: [
        {
          gas: '0xf4240',
          gasPrice: '0x2540be401',
          from: '0x9257e1aeb58e16a9c33e0e8469a1d5205d6350b8',
          to: '0x0a9dfacdeed4f3d433998b6a80ce0a272715e125',
          value: '0x16345785d8a0000'
        }
      ],
      callback: undefined
    }

      at src/evm/rpc.integration.spec.ts:58:15

  console.error
    Unhandled error

      at process.uncaught (node_modules/jest-jasmine2/build/jasmine/Env.js:248:21)

  console.error
    Error: Transaction check error: 
    # 2021-11-15 18:35:35 [pid: 7] [pidns: 4026532322]
    ERROR: InsufficientBalance, origin: 0x9257e1aeb58e16a9c33e0e8469a1d5205d6350b8, actual balance 0, but expected payment 110000000001000000
    |-- file: src/components/contracts/modules/ethereum/src/lib.rs
    |-- line: 189
    `-- column: 24
    

  console.log
    🚀 ~ ERROR file: rpc.spec.ts ~ line 51 ~ error Error: Transaction check error: 
    # 2021-11-15 18:35:35 [pid: 7] [pidns: 4026532322]
    ERROR: InsufficientBalance, origin: 0x9257e1aeb58e16a9c33e0e8469a1d5205d6350b8, actual balance 0, but expected payment 110000000001000000
    |-- file: src/components/contracts/modules/ethereum/src/lib.rs
    |-- line: 189
    `-- column: 24

 FAIL  src/evm/rpc.integration.spec.ts (148.399 s)
  Api Endpoint (rpc test) for "https://prod-testnet.prod.findora.org:8545"
    eth_protocolVersion
      ✕ Returns the current ethereum protocol version (356 ms)
    eth_chainId
      ✕ Returns the current chain id (253 ms)
    eth_accounts
      ✕ Returns a list of addresses owned by client (245 ms)
    eth_getBalance
      ✕ Returns the balance of the account of given address (253 ms)
    eth_sendTransaction
      ✕ Creates new message call transaction or a contract creation, if the data field contains code (238 ms)
    eth_call
      ✕ Executes a message immediately without creating a transaction (236 ms)
    eth_coinbase
      ✕ Returns the client coinbase address (239 ms)
    eth_gasPrice
      ✕ Returns the current price per gas in wei (251 ms)
    eth_blockNumber
      ✕ Returns the number of most recent block (247 ms)
    eth_getBlockByHash
      ✕ Returns information about a block by hash (260 ms)
    eth_getBlockByNumber
      ✕ Returns information about a block by block number. (242 ms)
    eth_getTransactionCount
      ✕ Returns the number of transactions SENT from an address (251 ms)
    eth_getBlockTransactionCountByHash
      ✕ Returns the number of transactions in a block from a block matching the given block hash (247 ms)
    eth_getBlockTransactionCountByNumber
      ✕ Returns the number of transactions in a block from a block matching the given block number (237 ms)
    eth_getCode
      ✕ Returns code at a given address (236 ms)
    eth_sendRawTransaction
      ✕ Creates new message call transaction or a contract creation for signed transactions (negative case) (241 ms)
    eth_estimateGas
      ✕ Generates and returns an estimate of how much gas is necessary to allow the transaction to complete (245 ms)
    eth_getTransactionByHash
      ✕ Returns the information about a transaction requested by transaction hash (246 ms)
    eth_getTransactionByBlockHashAndIndex
      ✕ Returns information about a transaction by block hash and transaction index position (248 ms)
    eth_getTransactionByBlockNumberAndIndex
      ✕ Returns information about a transaction by block number and transaction index position (245 ms)
    eth_getTransactionReceipt
      ✕ Returns the receipt of a transaction by transaction hash (251 ms)
    eth_getLogs
      ✕ Returns an array of all logs matching a given filter object (250 ms)

```

however all works well on forge 

```
  console.log
    🚀 ~ rpcParams.rpcUrl https://prod-forge.prod.findora.org:8545

      at Object.<anonymous> (src/evm/rpc.integration.spec.ts:30:9)

  console.log
    🚀 ~ IT IS SENDING file: rpc.spec.ts ~ line 37 ~ payload {
      method: 'eth_sendTransaction',
      params: [
        {
          gas: '0xf4240',
          gasPrice: '0x2540be401',
          from: '0x9257e1aeb58e16a9c33e0e8469a1d5205d6350b8',
          to: '0x0a9dfacdeed4f3d433998b6a80ce0a272715e125',
          value: '0x16345785d8a0000'
        }
      ],
      callback: undefined
    }

      at src/evm/rpc.integration.spec.ts:55:15

  console.log
    🚀 ~ IT IS SENT file: rpc.spec.ts ~ line 40 ~ payload {
      method: 'eth_sendTransaction',
      params: [
        {
          gas: '0xf4240',
          gasPrice: '0x2540be401',
          from: '0x9257e1aeb58e16a9c33e0e8469a1d5205d6350b8',
          to: '0x0a9dfacdeed4f3d433998b6a80ce0a272715e125',
          value: '0x16345785d8a0000'
        }
      ],
      callback: undefined
    }

      at src/evm/rpc.integration.spec.ts:58:15

  console.log
    🚀 ~ file: rpc.spec.ts ~ line 44 ~ hash 0xc88853017ca0ae9faf1d9dd7217129cdedb60b38920385edf542f9866da27565

      at src/evm/rpc.integration.spec.ts:61:15

  console.log
    🚀 ~ file: rpc.spec.ts ~ line 45 ~ receipt {
      blockHash: '0x47ec1bc3921391f610fac95fce778f3debf22252054886b563d25cefddf764bc',
      blockNumber: 245815,
      contractAddress: null,
      cumulativeGasUsed: 21000,
      from: '0x9257e1aeb58e16a9c33e0e8469a1d5205d6350b8',
      gasUsed: 21000,
      logs: [],
      logsBloom: '0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000',
      status: true,
      to: '0x0a9dfacdeed4f3d433998b6a80ce0a272715e125',
      transactionHash: '0xc88853017ca0ae9faf1d9dd7217129cdedb60b38920385edf542f9866da27565',
      transactionIndex: 0
    }

      at src/evm/rpc.integration.spec.ts:64:15

 PASS  src/evm/rpc.integration.spec.ts (38.679 s)
  Api Endpoint (rpc test) for "https://prod-forge.prod.findora.org:8545"
    eth_protocolVersion
      ✓ Returns the current ethereum protocol version (344 ms)
    eth_chainId
      ✓ Returns the current chain id (244 ms)
    eth_accounts
      ✓ Returns a list of addresses owned by client (245 ms)
    eth_getBalance
      ✓ Returns the balance of the account of given address (402 ms)
    eth_sendTransaction
      ✓ Creates new message call transaction or a contract creation, if the data field contains code (247 ms)
    eth_call
      ✓ Executes a message immediately without creating a transaction (252 ms)
    eth_coinbase
      ✓ Returns the client coinbase address (254 ms)
    eth_gasPrice
      ✓ Returns the current price per gas in wei (259 ms)
    eth_blockNumber
      ✓ Returns the number of most recent block (247 ms)
    eth_getBlockByHash
      ✓ Returns information about a block by hash (248 ms)
    eth_getBlockByNumber
      ✓ Returns information about a block by block number. (253 ms)
    eth_getTransactionCount
      ✓ Returns the number of transactions SENT from an address (240 ms)
    eth_getBlockTransactionCountByHash
      ✓ Returns the number of transactions in a block from a block matching the given block hash (244 ms)
    eth_getBlockTransactionCountByNumber
      ✓ Returns the number of transactions in a block from a block matching the given block number (250 ms)
    eth_getCode
      ✓ Returns code at a given address (242 ms)
    eth_sendRawTransaction
      ✓ Creates new message call transaction or a contract creation for signed transactions (negative case) (263 ms)
    eth_estimateGas
      ✓ Generates and returns an estimate of how much gas is necessary to allow the transaction to complete (262 ms)
    eth_getTransactionByHash
      ✓ Returns the information about a transaction requested by transaction hash (241 ms)
    eth_getTransactionByBlockHashAndIndex
      ✓ Returns information about a transaction by block hash and transaction index position (245 ms)
    eth_getTransactionByBlockNumberAndIndex
      ✓ Returns information about a transaction by block number and transaction index position (242 ms)
    eth_getTransactionReceipt
      ✓ Returns the receipt of a transaction by transaction hash (246 ms)
    eth_getLogs
      ✓ Returns an array of all logs matching a given filter object (270 ms)

Test Suites: 1 passed, 1 total
Tests:       22 passed, 22 total
Snapshots:   0 total
Time:        38.712 s, estimated 149 s
Ran all test suites matching /rpc.integration.spec.ts/i with tests matching "rpc test".
```

### Steps to reproduce
>1、
./fn account -a 0x9257e1aeb58e16a9c33e0e8469a1d5205d6350b8
>2、
 yarn test:emv:integration:rpc:devnet

**Comment by okovalov** [comment]
@kingpinXD well, not sure if that was redeployed. the internal transfer still does not seem to work 

<img width="940" alt="CleanShot 2021-11-30 at 14 03 45@2x" src="https://user-images.githubusercontent.com/1706749/144111171-a2ed4cf1-502e-422a-9a66-a68770a57cb7.png">

could not check the balance in the cli and in the metamask also have zeros.

<img width="598" alt="CleanShot 2021-11-30 at 14 02 39@2x" src="https://user-images.githubusercontent.com/1706749/144111108-47e172c5-ecf6-4943-87ce-bad1b1b1929b.png">

obviously no tests are passing since I need EVM FRA for that. 
<img width="940" alt="CleanShot 2021-11-30 at 14 04 46@2x" src="https://user-images.githubusercontent.com/1706749/144111322-1df1ef7a-372b-47f7-b036-4e8709d36dd9.png">

so, the bottom line - I think it is relevant.

**Comment by kingpinXD** [comment]
@okovalov  IS this env specific  ?
